version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpw123
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_DB: app
      RAILS_DB_USERNAME: postgres
      RAILS_DB_PASSWORD: testpw123
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db
